#!/bin/sh

ENABLED=yes
PROCS=haproxy_exporter
ARGS="--haproxy.scrape-uri=http://localhost:8404/stats?stats;csv"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
