#!/bin/sh

ENABLED=yes
PROCS=alertmanager
ARGS="--config.file=/opt/etc/prometheus/$PROCS.yml --storage.path=/opt/var/lib/$PROCS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
