#!/bin/sh

ENABLED=yes
PROCS=torrserver
ARGS="-d /opt/etc/torrserver"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
