#!/bin/sh

ENABLED=yes
PROCS=v2ray
ARGS="run -d /opt/etc/v2ray"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
