#!/bin/sh

ENABLED=yes
PROCS=collectd_exporter
ARGS="--collectd.listen-address=:25826"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
