#!/bin/sh

ENABLED=yes
PROCS=snmp_exporter
ARGS="--config.file=/opt/etc/prometheus/snmp_exporter/snmp.yml"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
