#!/bin/sh

ENABLED=yes
PROCS=go2rtc
ARGS="-c /opt/etc/$PROCS.yaml -d"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
