#!/bin/sh

ENABLED=yes
PROCS=sing-box
ARGS="run -D /opt/var/lib/sing-box -C /opt/etc/sing-box"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
