#!/bin/sh

ENABLED=yes
PROCS=sing-box
ARGS="run -D /opt/var/lib/$PROCS -C /opt/etc/$PROCS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
